{"name": "test_02_demo", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2\n  +1\n  -2", "trace": "self = <code2021-4-11.TestDemo object at 0x0000024218A2AE50>\n\n    @pytest.mark.skipif(age>18, reason=\"已成年，满足条件\")\n    @pytest.mark.test\n    def test_02_demo(self):\n        print(\"hello 222!\")\n>       assert 1==2\nE       assert 1 == 2\nE         +1\nE         -2\n\ncode2021-4-11.py:37: AssertionError"}, "start": 1618153147096, "stop": 1618153147096, "uuid": "4c60990d-7371-4674-ba4e-833da87d4727", "historyId": "f37c5508dd8f455c23c61882fd31ea30", "testCaseId": "edd68635cdc32fc8b5d5fc59178bdf08", "fullName": "code2021-4-11.TestDemo#test_02_demo", "labels": [{"name": "tag", "value": "test"}, {"name": "tag", "value": "@pytest.mark.skipif(False, reason='已成年，满足条件')"}, {"name": "suite", "value": "code2021-4-11"}, {"name": "subSuite", "value": "TestDemo"}, {"name": "host", "value": "SC-201811300146"}, {"name": "thread", "value": "14252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "code2021-4-11"}]}